CREATE TABLE GRUPO_PERMISSAO_PERMISSAO (
	GRUPO_PERMISSAO_ID BIGINT NOT NULL,
	PERMISSAO VARCHAR(255) NULL,
	CONSTRAINT GRUPO_PERMISSAO_PERMISSAO_UK UNIQUE (GRUPO_PERMISSAO_ID, PERMISSAO),
	CONSTRAINT GRUPO_PERMISSAO_FK FOREIGN KEY (GRUPO_PERMISSAO_ID) REFERENCES GRUPO_PERMISSAO(GRUPO_PERMISSAO_ID)
);