CREATE TABLE PROPRIO (
	PROPRIO_ID BIGINT NOT NULL,
	CHAVE VARCHAR(42) NULL,
	CHAVE_ANTERIOR VARCHAR(42) NULL,
	CONSTRAINT PROPRIO_PK PRIMARY KEY (PROPRIO_ID)
);

INSERT INTO PROPRIO (PROPRIO_ID, CHAVE, CHAVE_ANTERIOR) VALUES (1,NULL,NULL);