CREATE TABLE PEDIDO (
	PEDIDO_ID BIGINT NOT NULL,
	TAMANHO VARCHAR(50) NULL,
	SABOR VARCHAR(50) NOT NULL,
	CONSTRAINT PEDIDO_PK PRIMARY KEY (PEDIDO_ID),
	CONSTRAINT TAMANHO_CHK CHECK(TAMANHO IN ('PEQUENA','MEDIA','GRANDE')),
	CONSTRAINT SABOR_CHK CHECK(SABOR IN ('CALABRESA','MARGUERITA','PORTUGUESA'))
);

CREATE SEQUENCE PEDIDO_SQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;