CREATE TABLE GRUPO_USUARIO (
	USUARIO_ID BIGINT NOT NULL,
	GRUPO_PERMISSAO_ID BIGINT NOT NULL,
	CONSTRAINT GRUPO_USUARIO_UK UNIQUE (USUARIO_ID, GRUPO_PERMISSAO_ID),
	CONSTRAINT GRUPO_PERMISSAO_FK FOREIGN KEY (GRUPO_PERMISSAO_ID) REFERENCES GRUPO_PERMISSAO(GRUPO_PERMISSAO_ID),
	CONSTRAINT USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);