CREATE TABLE GRUPO_PERMISSAO (
	GRUPO_PERMISSAO_ID BIGINT NOT NULL,
	ATIVO BOOLEAN NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	CONSTRAINT GRUPO_PERMISSAO_PK PRIMARY KEY (GRUPO_PERMISSAO_ID)
);

CREATE SEQUENCE GRUPO_PERMISSAO_SQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;