CREATE TABLE USUARIO (
	USUARIO_ID BIGINT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	LOGIN VARCHAR(20) NULL,
	SENHA VARCHAR(100) NOT NULL,
	CLASSIFICACAO VARCHAR(50) NULL,
	ADMINISTRADOR BOOLEAN NOT NULL,
	DATA_AUTENTICACAO TIMESTAMP NULL,
	STATUS_REGISTRO VARCHAR(50) NOT NULL,
	DATA_INCLUSAO TIMESTAMP NOT NULL,
	DATA_ALTERACAO TIMESTAMP NOT NULL,
	DATA_EXCLUSAO TIMESTAMP NULL,
	CONSTRAINT USUARIO_PK PRIMARY KEY (USUARIO_ID),
	CONSTRAINT CLASSIFICACAO_CHK CHECK(CLASSIFICACAO IN ('SUPERVISOR','GERENTE','OPERADOR')),
	CONSTRAINT STATUS_REGISTRO_CHK CHECK(STATUS_REGISTRO IN ('ATIVO','INATIVO','EXCLUIDO'))
);

CREATE SEQUENCE USUARIO_SQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE;