CREATE TABLE PEDIDO_PERSONALIZACAO (
	PEDIDO_ID BIGINT NOT NULL,
	PERSONALIZACAO VARCHAR(50) NULL,
	CONSTRAINT PEDIDO_PERSONALIZACAO_UK UNIQUE (PEDIDO_ID, PERSONALIZACAO),
	CONSTRAINT PEDIDO_FK FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID)
);