CREATE TABLE GRUPO_PERMISSAO_ACESSO (
	GRUPO_PERMISSAO_ID BIGINT NOT NULL,
	ACESSO VARCHAR(255) NULL,
	CONSTRAINT GRUPO_PERMISSAO_ACESSO_UK UNIQUE (GRUPO_PERMISSAO_ID, ACESSO),
	CONSTRAINT GRUPO_PERMISSAO_FK FOREIGN KEY (GRUPO_PERMISSAO_ID) REFERENCES GRUPO_PERMISSAO(GRUPO_PERMISSAO_ID)
);